echo running script...

echo deleting auto scaling hpa...
kubectl delete hpa/backend --context kind-kind-1

echo deleting metrics server...
kubectl delete -f manifests/k8s/metrics-server.yaml --context kind-kind-1
