echo running script...

echo deleting auto scaling hpa...
kubectl delete hpa/backend --context kind-kind-1

echo deleting metrics server...
kubectl -nkube-system delete deploy/metrics-server --context kind-kind-1
