echo running stop script

echo deleteing ingress...
kubectl delete ingress backend-ingress-zone-aware

echo deleteing ingress controller...
kubectl delete -n ingress-nginx deploy ingress-nginx-controller

echo deleting service...
kubectl delete service backend-service-zone-aware

echo deleteing deployment...
kubectl delete deploy backend-zone-aware

echo deleteing cluster...
kind delete cluster --name kind-1
